version: '3.1'

services:

  app:
    build: .
    tty: true
    volumes:
      - .:/code
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
